[build]
  # The command to run your application
  cmd = "go run ./main.go"
  # Directory to store build logs
  log = "tmp/build.log"
  # Include the following file extensions in the build
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Exclude the following directories from the build
  exclude_dir = ["assets", "tmp", "vendor"]
  # These environment variables will be passed to the run command
  env = ["GOPATH", "GOROOT"]